<script src="<?php echo $this->getSkinUrl('js/jquery-1.2.6.noConflict.min.js'); ?>" type="text/javascript" ></script>
<script type="text/javascript">

jQuery.noConflict();
function applyto(id) {
var c= '#mks'+id
jQuery(c).fadeIn(1000);
}

function applytoprev(x,y) {
jQuery('#mks'+x).hide();
jQuery('#mks'+y).show();
}

function applytonext(x,y) {
jQuery('#mks'+x).hide();
jQuery('#mks'+y).show();
}
</script>

 
<style type="text/css">
.blankdiv{background-color:#000;
position:fixed;
z-index: 9001;
top:0px; height:100%;
left:0px;
width:100%; opacity: 0.65;
filter:alpha(opacity=65);}

#popupform{height: 100%;
    left: 0;
    padding: 15px;
    position: fixed;
    top: 0;
    width:97%;
    z-index: 10001; 
	}
	
#popupform .applyform{position:relative; overflow:auto;
background-color:#fff;
width:510px;
height:500px;  margin:5% auto auto auto;
z-index: 9002; padding:10px; border:10px solid #7F3814; }


#pclose{
   
  
    cursor: pointer;
    height: 25px;
    margin: 5% auto -6%;
    position: relative;
    right: -276px;
  
    top: 0;
    width: 25px;
    z-index: 9999;}
</style>

<h4><?php echo $this->__('Image Gallery') ?></h4>
<?php
$i = 0;
$collection = Mage::getModel('imagegallery/imagegallery')->getCollection();
                $collection->setPageSize(25);
                $collection->setCurPage(10);
                $size = $collection->getSize();
                $cnt = count($collection);
$vz=1;
foreach ($collection as $item) 
{
$i = $i+1;
$item->setTitle($i);
// echo $item->getTitle(); 
// echo $filename = $item-> getFilename();
$filenaeme =   $item-> getFilename();
?>
<?php $media_url =  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>
<div style="float:left;border: 1px solid;
    margin: 5px;">
<a href="javascript:void(0)"  onclick="applyto('<?php echo $vz; ?>')"><img src="<?php echo $media_url.$filenaeme; ?>"  height="100" width="100"/></a>
</div>
<div id="mks<?php echo $vz; ?>" style="display:none">
<div id="popupform">
<div class="blankdiv"></div>
<div id="pclose" onclick="javascript:document.getElementById('<?php echo 'mks'.$vz; ?>').style.display='none'">
<img src="<?php echo $this->getSkinUrl('images/close.png'); ?>" />
</div>
<div class="applyform">
<p id="contactArea">
<center>
<a href="javascript:void(0)"  onclick="applytoprev('<?php echo $vz; ?>' ,'<?php echo $vz-1; ?>')"><img src="<?php echo $this->getSkinUrl('images/left_1.png'); ?>" /></a><?php echo $vz; ?>
<img src="<?php echo $media_url.$filenaeme; ?>"  height="450" width="450" align="center"/>
<a href="javascript:void(0)"  onclick="applytonext('<?php echo $vz; ?>' ,'<?php echo $vz+1; ?>')"><img src="<?php echo $this->getSkinUrl('images/right_1.png'); ?>" /></a>
</center>
</p>
</div>
</div>
</div>
<?php 
$vz++;}
$collection->walk('save');
?> 


